document.addEventListener("click",myfunction);
function myfunction(){
    document.getElementById("1").addEventListener("click",function(){
        document.getElementById("i1").src="1.jpg";
    })
    document.getElementById("2").addEventListener("click",function(){
        document.getElementById("i2").src="2.jpg";
    })
    document.getElementById("3").addEventListener("click",function(){
        document.getElementById("i3").src="1.jpg";
    })
    document.getElementById("4").addEventListener("click",function(){
        document.getElementById("i4").src="3.jpg";
    })
    document.getElementById("5").addEventListener("click",function(){
        document.getElementById("i5").src="5.jpg";
    })
    document.getElementById("6").addEventListener("click",function(){
        document.getElementById("i6").src="6.jpg";
    })
    document.getElementById("7").addEventListener("click",function(){
        document.getElementById("i7").src="2.jpg";
    })
    document.getElementById("8").addEventListener("click",function(){
        document.getElementById("i8").src="5.jpg";
    })
    document.getElementById("9").addEventListener("click",function(){
        document.getElementById("i9").src="3.jpg";
    })
    document.getElementById("10").addEventListener("click",function(){
        document.getElementById("i10").src="4.jpg";
    })
    document.getElementById("11").addEventListener("click",function(){
        document.getElementById("i11").src="6.jpg";
    })
    document.getElementById("12").addEventListener("click",function(){
        document.getElementById("i12").src="4.jpg";
    })
}